#!/usr/bin/env bash

set -e

mkdir -p gen

echo "# Code generated by protoc - DO NOT EDIT" &> gen/README.md

mkdir -p gen/web
echo "Generating protobuf for gRPC-web ts"
protoc -I./src --js_out=import_style=commonjs:gen/web --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:gen/web chat.proto

mkdir -p gen/go
echo "Generating protobuf for gRPC golang"
protoc -I./src --go_out=plugins=grpc:gen/go chat.proto
